samplesheet: "config/samples.tsv"
samples:
  include:
    - foo
  exclude:
    - bar

# Databases
krakenuniq_db: resources/krakendb
pathogenomesFound: resources/pathogenomesFound.tab
pathogenome_seqid2taxid_db: resources/seqid2taxid.pathogen.map
bowtie2_patho_db: resources/bowtie2db
malt_seqid2taxid_db: resources/malt_seq2tax
malt_nt_fasta: resources/maltntfasta
malt_accession2taxid: resources/malt_acc2tax
ncbi_db: resources/ncbi

# Breadth and depth of coverage filters    
n_unique_kmers: 1000
n_tax_reads: 200

