samplesheet: resources/samples.tsv
samples:
  include:
    - foo
    - bar
  exclude:
    - foobar

analyses:
  mapdamage: true
  authentication: true
  malt: true

adapters:
  illumina: true
  nextera: false
  custom: []
  

# Databases
krakenuniq_db: resources/KrakenUniq_DB
bowtie2_db: resources/ref.fa
pathogenomesFound: resources/pathogenomesFound.tab
bowtie2_seqid2taxid_db: resources/seqid2taxid.pathogen.map
malt_seqid2taxid_db: resources/KrakenUniq_DB/seqid2taxid.map
malt_nt_fasta: resources/ref.fa
malt_accession2taxid: resources/accession2taxid.map
ncbi_db: resources/ncbi

# Breadth and depth of coverage filters
n_unique_kmers: 1000
n_tax_reads: 200
