name: aMeta

channels:
  - conda-forge
  - bioconda

dependencies:
  # core packages for workflow
  - python>=3.11
  - snakemake-minimal>=6.0,<8
  - mamba
  - pandas
  - biopython
  - fastqc>=0.12.1
  - mapdamage2
  - multiqc
  - bowtie2
  - samtools
  - cutadapt
  - krakenuniq
  - krona
  - r-base
  - hops
  - seqtk
  - parallel
  - megan
  - r-pheatmap
  - pmdtools
  - pysam

  # packages required to create snakemake reports
  - pygments
  - jinja2
  - networkx
  - pygraphviz
  - imagemagick
  - graphviz
  - pandoc
